### ISSUE TITLE
Can't run PlistPal from mint

### ISSUE THREAD

**Issue by dungi** [liamnichols/PlistPal#1]
Hey I tried to run

`mint run PlistPal plistpal`

But PlistPal couldn't be found anymore. Can you provide any help? Or is it possible to run it through Xcode somehow with SPM?

**Comment by liamnichols** [comment]
Hey @dungi, I assume that you might have figured it out but if you are not using a `Mintfile` then you have to include my username as well so the command should be the following:

```
mint run liamnichols/PlistPal plistpal
```

let me know if you still had issues! Thanks
